services:
  mongo:
    image: mongo
    restart: on-failure
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express
    restart: always
    container_name: roll_adminer_db
    ports:
      - 8881:8081

