services:
  mongo:
    image: mongo
    restart: on-failure
    container_name: roll_db
    ports:
      - '27017:27017'
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: login
    #   MONGO_INITDB_ROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    restart: always
    container_name: roll_adminer_db
    ports:
      - 8091:8081
#     environment:
#       ME_CONFIG_MONGODB_ADMINUSERNAME: login
#       ME_CONFIG_MONGODB_ADMINPASSWORD: password

# mongo:
#   image: mongo:latest
#   container_name: roll_db
#   volumes:
#     - /data/db/mongo
#   ports:
#     - 27017:27017

# mongo-express:
#   image: mongo-express
#   container_name: roll_adminer_db
#   restart: always
#   ports:
#     - 8081:8081
